"""ADC noise and nonlinearity models.

Processing order matches ``veriloga/configurable_adc.va``:
  jitter → gain/offset → A2/A3 → thermal → DNL → quantize.

Signal-chain equations (input-referred unless noted):
  - Jitter: ``Δv = jitter_rms_s · dv/dt · N(0,1)`` (V), aperture noise in seconds.
  - Gain/offset: ``v = gain·v + offset_v`` (V).
  - Nonlinearity: normalized ``x = (v - Vcm)/Vfs``,
    ``v += Vfs·(a2·x² + a3·x³)`` (dimensionless ``a2``, ``a3``).
  - Thermal: ``v += N(0, sigma_thermal_v)`` (V).
  - DNL: add fixed per-code threshold offset from :func:`build_dnl_profile` (V).

``apply_analog_front_end_at_edges`` applies that chain once per clock edge so
Python/ngspice post-process matches Spectre ``@(cross(clk))`` sampling.

Seeds: ``noise_seed`` drives thermal/jitter draws; DNL profile uses ``noise_seed + 17``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from adc_model.config import AdcConfig, AdcNoiseConfig

# Upper bound for Spectre edge-noise LUTs (10-bit static @ 16 samples/code = 16384).
MAX_EDGE_DRAWS = 65536


def build_edge_normal_draws(
    noise: AdcNoiseConfig,
    num_edges: int,
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    """Build per-edge standard-normal draws matching :func:`apply_analog_front_end_at_edges`.

    Draw order per edge: jitter (if enabled), then thermal (if enabled), all from
    ``noise_seed`` — independent of the DNL profile seed ``noise_seed + 17``.

    Args:
        noise: Noise configuration (jitter / thermal enable flags and seed).
        num_edges: Number of ADC clock edges in the capture.

    Returns:
        ``(jitter_draws, thermal_draws)`` arrays of length ``num_edges``. Unused
        mechanisms are zero-filled.
    """
    if num_edges < 0:
        msg = f"num_edges must be non-negative, got {num_edges}"
        raise ValueError(msg)

    rng = np.random.default_rng(noise.noise_seed)
    jitter = np.zeros(num_edges, dtype=np.float64)
    thermal = np.zeros(num_edges, dtype=np.float64)
    for edge in range(num_edges):
        if noise.jitter_rms_s > 0.0:
            jitter[edge] = float(rng.normal())
        if noise.sigma_thermal_v > 0.0:
            thermal[edge] = float(rng.normal())
    return jitter, thermal


def write_edge_noise_include(
    noise: AdcNoiseConfig,
    num_edges: int,
    path: Path,
) -> Path:
    """Write Verilog-A assignments for Python-matched jitter/thermal normal draws.

    Args:
        noise: Noise settings and ``noise_seed`` for the edge draw stream.
        num_edges: LUT depth (one row per ``@(cross(clk))`` conversion).
        path: Destination ``edge_noise.inc`` path.

    Returns:
        Resolved output path.
    """
    if num_edges > MAX_EDGE_DRAWS:
        msg = f"num_edges={num_edges} exceeds MAX_EDGE_DRAWS={MAX_EDGE_DRAWS}"
        raise ValueError(msg)

    jitter, thermal = build_edge_normal_draws(noise, num_edges)
    lines = [
        "// Auto-generated by adc_model.noise.write_edge_noise_include",
        f"// noise_seed={noise.noise_seed}, num_edges={num_edges}",
        f"                edge_noise_count = {num_edges};",
    ]
    for edge in range(num_edges):
        lines.append(f"                jitter_normal[{edge}] = {jitter[edge]:.16e};")
        lines.append(f"                thermal_normal[{edge}] = {thermal[edge]:.16e};")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path.resolve()


def write_dnl_profile_include(
    cfg: AdcConfig,
    noise: AdcNoiseConfig,
    path: Path,
) -> Path:
    """Write a Verilog-A include with per-code DNL offsets from :func:`build_dnl_profile`.

    The Spectre driver prepends ``define CONFIGURABLE_ADC_USE_PYTHON_DNL`` to a
    rendered copy of ``configurable_adc.va`` and places this file beside it as
    ``dnl_profile.inc`` so AHDL DNL matches Python/ngspice exactly.

    Args:
        cfg: ADC configuration (determines code count and LSB scale).
        noise: Noise settings (``dnl_sigma_lsb``, ``noise_seed + 17`` profile seed).
        path: Destination ``.inc`` path (parent directories are created).

    Returns:
        Resolved output path.
    """
    profile = build_dnl_profile(cfg, noise)
    lines = [
        "// Auto-generated by adc_model.noise.write_dnl_profile_include",
        f"// noise_seed={noise.noise_seed}, dnl_sigma_lsb={noise.dnl_sigma_lsb}",
    ]
    limit = min(len(profile), cfg.max_code + 1, 4096)
    for code_idx in range(limit):
        lines.append(f"                dnl_offset[{code_idx}] = {profile[code_idx]:.16e};")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path.resolve()


def build_dnl_profile(cfg: AdcConfig, noise: AdcNoiseConfig) -> NDArray[np.float64]:
    """Build a fixed per-code DNL threshold offset profile in volts.

    Draws ``N(0, dnl_sigma_lsb)`` per code (LSB), scales by ``cfg.lsb`` (V/LSB),
    and returns one offset per quantizer level (length ``num_codes``).
    """
    # Offset seed so DNL draws are independent of per-sample thermal draws.
    rng = np.random.default_rng(noise.noise_seed + 17)
    offsets_lsb = rng.normal(0.0, noise.dnl_sigma_lsb, cfg.num_codes)
    return offsets_lsb * cfg.lsb


def apply_analog_front_end(
    vin: NDArray[np.float64],
    cfg: AdcConfig,
    noise: AdcNoiseConfig,
    *,
    dt: float,
    rng: np.random.Generator,
    dnl_profile: NDArray[np.float64] | None = None,
) -> NDArray[np.float64]:
    """Apply jitter, gain/offset, nonlinearity, and thermal noise.

    Args:
        vin: Input voltage samples (V) on the simulation grid.
        dt: Uniform time step between samples (s).
        rng: Generator for jitter and thermal draws (seeded from ``noise_seed``).
        dnl_profile: Optional per-code offsets (V) indexed by estimated code.

    Returns:
        Front-end voltage (V) before quantization.
    """
    num_samples = len(vin)
    v = vin.astype(np.float64, copy=True)

    if noise.jitter_rms_s > 0.0 and num_samples > 1:
        dv_dt = np.gradient(v, dt)
        jitter_v = noise.jitter_rms_s * dv_dt
        jitter_v *= rng.normal(0.0, 1.0, num_samples)
        v += jitter_v

    v = cfg.gain * v + cfg.offset_v

    vfs = cfg.vrefp - cfg.vrefn
    vcm = 0.5 * (cfg.vrefp + cfg.vrefn)
    if vfs > 0.0 and (noise.nonlinearity_a2 != 0.0 or noise.nonlinearity_a3 != 0.0):
        x = (v - vcm) / vfs
        v += vfs * (noise.nonlinearity_a2 * x**2 + noise.nonlinearity_a3 * x**3)

    if noise.sigma_thermal_v > 0.0:
        v += rng.normal(0.0, noise.sigma_thermal_v, num_samples)

    if dnl_profile is not None and np.any(dnl_profile != 0.0):
        code_est = np.floor((v - cfg.vrefn) / cfg.lsb).astype(np.int64)
        code_est = np.clip(code_est, 0, cfg.max_code - 1)
        v += dnl_profile[code_est]

    return v


def apply_analog_front_end_at_edges(
    vin: NDArray[np.float64],
    edge_idx: NDArray[np.int64],
    cfg: AdcConfig,
    noise: AdcNoiseConfig,
    *,
    dt: float,
    rng: np.random.Generator,
    dnl_profile: NDArray[np.float64] | None = None,
) -> NDArray[np.float64]:
    """Apply the analog front end once per clock edge (Verilog-A sampling).

    Args:
        vin: Input ramp or tone sampled on the simulation time grid.
        edge_idx: Rising-edge indices into ``vin``.
        cfg: ADC configuration.
        noise: Noise / nonlinearity settings.
        dt: Uniform time step between grid points (s).
        rng: Retained for API compatibility; edge draws come from
            :func:`build_edge_normal_draws` (``noise_seed`` stream).
        dnl_profile: Optional per-code DNL threshold offsets (V).

    Returns:
        Front-end voltage at each edge, ready for quantization.
    """
    _ = rng
    n_edges = len(edge_idx)
    v_front = np.empty(n_edges, dtype=np.float64)
    vcm = 0.5 * (cfg.vrefp + cfg.vrefn)
    vfs = cfg.vrefp - cfg.vrefn
    vin_prev = vcm
    jitter_draws, thermal_draws = build_edge_normal_draws(noise, n_edges)

    for k in range(n_edges):
        idx = int(edge_idx[k])
        vin_sample = float(vin[idx])
        # Jitter uses local dv/dt; on dense grids ``dt_sample`` spans multiple UI.
        if k == 0:
            dt_sample = 1.0
        else:
            dt_sample = float((idx - int(edge_idx[k - 1])) * dt)
            if dt_sample <= 0.0:
                dt_sample = dt

        v_eff = vin_sample
        if noise.jitter_rms_s > 0.0:
            dv_dt = (vin_sample - vin_prev) / dt_sample
            v_eff += noise.jitter_rms_s * dv_dt * jitter_draws[k]

        v_eff = cfg.gain * v_eff + cfg.offset_v

        if vfs > 0.0 and (noise.nonlinearity_a2 != 0.0 or noise.nonlinearity_a3 != 0.0):
            x_norm = (v_eff - vcm) / vfs
            v_eff += vfs * (
                noise.nonlinearity_a2 * x_norm * x_norm
                + noise.nonlinearity_a3 * x_norm * x_norm * x_norm
            )

        if noise.sigma_thermal_v > 0.0:
            v_eff += noise.sigma_thermal_v * thermal_draws[k]

        if dnl_profile is not None and noise.dnl_sigma_lsb > 0.0:
            code_idx = int(np.floor((v_eff - cfg.vrefn) / cfg.lsb))
            code_idx = int(np.clip(code_idx, 0, cfg.max_code - 1))
            v_eff += dnl_profile[code_idx]

        v_front[k] = v_eff
        vin_prev = vin_sample

    return v_front


def apply_post_front_end_noise(
    v_front: NDArray[np.float64],
    cfg: AdcConfig,
    noise: AdcNoiseConfig,
    *,
    rng: np.random.Generator,
    dnl_profile: NDArray[np.float64] | None = None,
) -> NDArray[np.int64]:
    """Apply thermal noise, DNL spread, and quantization after the analog front end.

    Used when ngspice stops at ``v_nl`` (nonlinearity output) and Python must
    finish thermal + DNL + ``quantize_front_end`` with the same ``noise_seed``
    as the behavioral model. Jitter/gain/nonlinearity are assumed already in ``v_front``.

    Returns:
        Integer ADC codes (0 .. ``max_code``).
    """
    v = v_front.astype(np.float64, copy=True)
    num_samples = len(v)

    if noise.sigma_thermal_v > 0.0:
        v += rng.normal(0.0, noise.sigma_thermal_v, num_samples)

    if dnl_profile is not None and np.any(dnl_profile != 0.0):
        code_est = np.floor((v - cfg.vrefn) / cfg.lsb).astype(np.int64)
        code_est = np.clip(code_est, 0, cfg.max_code - 1)
        v += dnl_profile[code_est]

    return quantize_front_end(v, cfg)


def quantize_front_end(
    v_front: NDArray[np.float64],
    cfg: AdcConfig,
) -> NDArray[np.int64]:
    """Quantize analog front-end samples to integer codes.

    Mid-tread mapping (matches VA):
      ``code = floor((v_front - vrefn) / (vrefp - vrefn) * max_code + 0.5)``
    then clip to ``[0, max_code]``. ``v_front`` is in volts; output is unitless code.
    """
    if np.any(cfg.lsb <= 0.0):
        msg = "LSB must be positive."
        raise ValueError(msg)

    fs_range = cfg.vrefp - cfg.vrefn
    code_real = (v_front - cfg.vrefn) / fs_range * cfg.max_code
    codes = np.floor(code_real + 0.5).astype(np.int64)
    return np.clip(codes, 0, cfg.max_code).astype(np.int64)
